"""Reproduce manually curated projections; no retrieval, model run, or empirical pilot."""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATE = '2026-09-08'
URLS = ['https://academic.oup.com/qje/article/140/2/889/7990658', 'https://shakkednoy.com/Noy%20Zhang%20NBER%20SI.pdf', 'https://pubsonline.informs.org/doi/10.1287/orsc.2025.21838']
TITLES = ['Generative AI at Work', 'Experimental evidence on the productivity effects of generative artificial intelligence', 'Navigating the Jagged Technological Frontier: Field Experimental Evidence of the Effects of Artificial Intelligence on Knowledge Worker Productivity and Quality']
AUTHORS = [['Erik Brynjolfsson','Danielle Li','Lindsey Raymond'],['Shakked Noy','Whitney Zhang'],['Fabrizio Dell’Acqua','Edward McFowland III','Ethan Mollick','Hila Lifshitz-Assaf','Katherine C. Kellogg','Saran Rajendran','Lisa Krayer','François Candelon','Karim R. Lakhani']]
DOIS = ['10.1093/qje/qjae044','10.1126/science.adh2586','10.1287/orsc.2025.21838']
LOCATORS = ['Abstract; III.B and Table I; IV.A and Table II; IV.B; VIII', 'Author manuscript pp. 1, 3–4, 7; Figure 1 (p. 12)', 'Sections 3 and 4.2; Figure 5; Table 7']

def make(lang):
 def t(en,zh): return zh if lang=='zh' else en
 q=t('Should an enterprise customer-support team introduce a generative AI assistant?', '企业客服团队是否应引入生成式 AI 助手？')
 sources=[]
 for i in range(3):
  sources.append(dict(source_id=f'S-00{i+1}',title=TITLES[i],authors=AUTHORS[i],year=[2025,2023,2026][i],doi=DOIS[i],canonical_url=URLS[i],source_type='journal_article',authority_level='tier1_paper_doi',status='VALID',source_locator={'type':'section','section':LOCATORS[i]},fetch={'original_url':URLS[i],'fetch_method':'native','fetch_provider':'builtin','fetch_status':'FETCH_VALID'},extensions={'verified_on':DATE,'data_origin':'manual_curated','version': ['published QJE article','author manuscript associated with Science 2023; not the March 444-person draft','published Organization Science 2026 article'][i], 'verification_scope':'Full primary text read through web tool; no Crossref registry or retraction check claimed.'}))
 frame={'question':q,'decision_object':'adopt','intervention':{'policy_name':'human_supervised_customer_support_assistant','policy_type':'institutional_reform','mechanism':'approved_knowledge_base_and_agent_review'},'population':{'target_group':'enterprise_customer_support_staff','excluded_groups':'autonomous_agents_and_high_stakes_specialist_advice'},'comparison':t('Existing support workflow without generative AI suggestions.','不提供生成式 AI 建议的现有客服流程。'),'outcomes':{'primary':['policy_effectiveness','implementation_risk'],'secondary':['cost_effectiveness','equity','feasibility']},'context':{'policy_environment':'enterprise_customer_support'},'scope':{'time_range':'2023–2026','evidence_types':['quasi_experimental','rct']},'success_condition':t('Improve verified resolutions per paid staff hour while preserving service quality, privacy and staff autonomy.','提高每付薪工时的有效解决量，同时维持服务质量、隐私和员工自主判断。'),'extensions':{'domain':'policy','data_origin':'manual_curated','note':t('Purposive evidence selection, not a systematic review or model execution benchmark.','目的性人工选编，不是系统综述，也不属于模型执行 benchmark。')}}
 claim_texts=[t('AI assistance can shorten customer chat handling in a bounded support setting; throughput is a separate outcome.','在有边界的客服场景中，AI 辅助可缩短会话处理时间；吞吐量是另一项指标。'), t('ChatGPT reduced time on short professional writing tasks; this is indirect evidence for customer support.','ChatGPT 缩短了短篇职业写作任务用时；对客服而言属于间接证据。'), t('AI can reduce correctness on tasks outside its capability frontier; consulting evidence is indirect for support.','在超出能力边界的任务中 AI 可能降低正确率；咨询实验对客服属于间接证据。'),t('Experienced, high-skill support staff need separate quality monitoring rather than assumed uniform benefits.','须单独监测资深高技能客服的质量，不能假定所有岗位群体均受益。')]
 limitations=[t('One firm, one tool and a staggered nonrandom rollout; causal interpretation depends on identification assumptions.','单一企业、单一工具、非随机分批上线；因果解释依赖识别假设。'),t('Indirect evidence, not directly generalizable: brief incentivized writing tasks did not demand precise factual accuracy or customer-specific context.','间接证据，不可直接推广：短时激励写作任务不要求精确事实或客户特定情境。'),t('Indirect evidence, not directly generalizable: consultants solving an experimental business case, not live customer tickets.','间接证据，不可直接推广：咨询顾问处理实验商业案例，并非真实客服工单。'),t('Same study as E-001; subgroup sample size was not extracted. This is not an independent replication.','与 E-001 属于同一研究；未提取该亚组样本量，不是独立重复验证。')]
 evidence=[]
 for i in range(4):
  si=[0,1,2,0][i]; eid=f'E-00{i+1}'; cid=f'C-00{i+1}'
  measure=[t('Chat handling time; separate throughput summary: about 15% more issues resolved per hour.','会话处理时间；另列吞吐量摘要：每小时解决问题数约增加 15%。'),t('Self-reported task time: approximately 40% lower; assessed writing quality approximately 18% higher is a separate measure.','自报任务用时约减少 40%；评定写作质量约提高 18% 是另一项指标。'),t('Correct business recommendation: about 19 percentage points lower across AI arms; Table 7 has 373 participants, not 758.','商业建议正确率：合并 AI 组约低 19 个百分点；表 7 为 373 人，不是 758 人。'),t('Small quality declines among the most experienced and highest-skilled support staff.','资历最深、技能最高的客服群体出现小幅质量下降。')][i]
  raw=[{'metric':'issues_resolved_per_hour_relative_change','value':15,'unit':'percent','role':'separate_throughput_measure_not_completion_time'}, {'metric':'task_time_relative_change','value':-40,'unit':'percent'}, {'metric':'correctness_absolute_change','value':-19,'unit':'percentage_points'}, {'metric':'experienced_staff_quality','value':None,'unit':'not_extracted'}][i]
  raw.update(ci_lower=None,ci_upper=None,p_value=None,uncertainty_status='not_extracted_for_this_summary_estimand')
  evidence.append({'evidence_id':eid,'source_id':f'S-00{si+1}','study_id':f'ST-00{si+1}','sample_id':['SAMPLE-support-all','SAMPLE-writing','SAMPLE-consulting-outside','SAMPLE-support-all'][i],'claim_id':cid,'title':TITLES[si],'year':[2025,2023,2026,2025][i],'study_type':['quasi_experimental','rct','rct','quasi_experimental'][i],'population':[t('Customer-support agents','客服人员'),t('College-educated working professionals','受过大学教育的职场人士'),t('BCG consultants in the outside-frontier experiment','参与超出能力边界实验的 BCG 顾问'),t('Experienced and high-skill customer-support agents','资深高技能客服人员')][i],'sample_size':[5172,453,373,None][i],'outcome_type':['completion_time','completion_time','accuracy','accuracy'][i],'outcome_measure':measure,'claim':claim_texts[i],'direction':'support','relation_to_claim':'support','effect_direction':['positive','positive','negative','negative'][i],'decision_relation':'conditional','source_location':URLS[si], 'limitations':[limitations[i]],'status':'SUPPORTED','extensions':{'domain':'policy','policy_outcome':['policy_effectiveness','policy_effectiveness','implementation_risk','implementation_risk'][i],'directness':['direct','indirect','indirect','direct'][i],'raw_result':raw,'standardized_effect':None,'study_total_n':[5172,453,758,5172][i],'note':t('Row-specific sample; study_total_n must not replace the analyzed sample. E-004 shares the S-001 cohort and is not separately counted.','按条目注明样本；研究总人数不得替代分析样本。E-004 属于 S-001 同一队列，不另计独立样本。')}})
 stop=[t('Pause immediately after a verified privacy leak or a serious unsafe or unauthorized customer commitment; investigate before resuming.','一旦核实隐私泄漏、严重不安全建议或越权客户承诺，立即暂停，调查后再决定是否恢复。'),t('Pause expansion if blinded quality review crosses a pre-agreed noninferiority margin, including within experience strata.','若盲评质量越过预先约定的非劣界值（包括各资历分层），暂停扩展。')]
 conditions=[t('Start with low-risk, knowledge-base-covered queues; agents inspect and edit every proposed reply.','从低风险且知识库覆盖的队列开始；客服审查并编辑每条建议回复。'),t('Stratify by tenure and baseline skill; retain expert discretion and measure review workload.','按资历和基线技能分层；保留专家判断并记录复核工作量。'),t('Minimize and redact customer data, restrict access and retention, and review supplier data-use terms before a pilot.','试点前落实客户数据最小化与脱敏、访问和留存限制，并审查供应商数据使用条款。'),t('Escalate unfamiliar, ambiguous, sensitive or high-stakes requests to qualified humans; no autonomous commitments.','陌生、模糊、敏感或高风险请求交由合格人员处理；禁止自动作出承诺。')]
 gaps=[t('Local net cost, privacy incident rates, subgroup service quality and sustained performance are not established by this selected evidence set.','这组选编证据尚未确立本企业净成本、隐私事件率、亚组服务质量及持续表现。')]
 decision={'decision_question':q,'target_population':t('Enterprise customer-support staff, stratified by tenure and baseline skill.','企业客服人员，按资历和基线技能分层。'),'target_context':t('Human-supervised support using an approved knowledge base.','使用经审核知识库、由人工监督的客服流程。'),'recommended_action':'pilot','confidence':'Low','confidence_score':None,'independent_studies':3,'independent_samples':3,'supported_claims':claim_texts,'uncertain_claims':gaps,'decision_rationale':t('A supervised pilot is warranted because one direct field study supports efficiency gains but also reveals heterogeneous quality effects. Indirect experiments identify task boundaries, while local safety and net value remain unknown.','建议有监督试点：一项直接现场研究支持效率收益，但同时显示质量效应因人而异。间接实验提示任务边界，而本地安全性与净价值仍未知。'),'methodology_summary':t('One staggered-rollout quasi-experiment and two randomized experiments. Only the support study is direct; no pooled standardized effect or model benchmark was computed.','一项分批上线准实验和两项随机实验。只有客服研究属于直接证据；未计算合并标准化效应或模型 benchmark。'),'what_cannot_be_claimed':[t('Universal gains, autonomous deployment safety, privacy protection, reduced staffing requirements or educational learning gains.','普遍收益、自动部署安全、隐私保护、减员必要性或教学学习效果。')],'missing_evidence':gaps,'applicability':{'required_conditions':conditions},'extensions':{'data_origin':'manual_curated','benchmark_eligible':False,'note':t('Conservative manual judgment about broad deployment; not a deterministic confidence-policy run or a probability.','针对全面部署的保守人工判断；不是确定性置信度策略运行结果，也不是概率。'),'knowledge_gaps':[{'gap_id':'G-001','evidence_ids':['E-001','E-002','E-003','E-004'],'summary':gaps[0]}]}}
 intervention={'decision':'pilot','target_population':t('Enterprise customer-support staff, stratified by tenure and baseline skill.','企业客服人员，按资历和基线技能分层。'),'pilot_duration':t('Proposed: two baseline weeks and six pilot weeks; not executed.','建议：两周基线和六周试点；尚未执行。'),'ai_usage_policy':conditions[0],'risk_control':conditions,'stop_conditions':stop,'evidence_alignment':['E-001','E-002','E-003','E-004'],'extensions':{'gap_id':'G-001','target_population':'enterprise_customer_support_staff','status':'proposed_not_executed'}}
 evaluation={'research_question':q,'groups':{'treatment':t('Eligible teams randomly assigned to supervised assistant access, stratified by tenure and baseline performance.','符合条件的团队按资历与基线表现分层，随机分配有监督助手使用权限。'),'comparison':t('Concurrent teams retaining the existing workflow; document contamination.','同期维持现有流程的团队；记录组间污染。')},'baseline':t('Record resolution rate, paid hours, repeat contacts, blinded quality and review costs before allocation.','分配前记录解决率、付薪工时、重复联系、盲评质量及复核成本。'),'post_test':t('Assess the same outcomes at pilot end; separately audit privacy and unsafe commitments.','试点结束时评估相同结果；独立审计隐私与不安全承诺。'),'analysis_plan':t('Preregister an intention-to-treat comparison with team-clustered uncertainty and subgroup estimates. Set sample size and noninferiority margins from local baseline variance and operational priorities before enrollment.','入组前预注册意向治疗比较、团队聚类不确定性及亚组估计。根据本地基线变异和业务目标确定样本量与非劣界值。'),'success_threshold':t('Expand only if quality is noninferior, verified resolutions per paid hour improve, net cost is acceptable and no serious unresolved safety incident remains; thresholds require local agreement.','仅在质量非劣、每付薪工时有效解决量提高、净成本可接受且无未解决严重安全事件时考虑扩展；阈值须在本地预先约定。'),'stop_conditions':stop,'extensions':{'gap_id':'G-001','status':'proposed_not_executed'}}
 methodology={'target':'overall','verdict':'CONCERN','audit_items':{k:{'status':v} for k,v in {'evidence_level':'met','causal_identification':'partial','external_validity':'partial','cost_evidence':'missing','stakeholder_representation':'partial','implementation_evidence':'partial','equity_analysis':'partial','effect_size_reported':'partial','uncertainty_quantified':'partial','comparator_clarity':'met','publication_bias_risk':'partial','generalizability_claims':'met'}.items()},'task_vs_learning_guard':{'measured_construct':'workplace_task_performance','equates_task_with_learning':False,'note':t('Teaching outcomes are not applicable; productivity is not a claim about student learning.','教学结果不适用；生产率并非学生学习效果主张。')},'limitations':limitations,'suggestions':conditions,'extensions':{}}
 claims=[{'claim_id':e['claim_id'],'claim':e['claim'],'outcome_type':e['outcome_type'],'evidence_ids':[e['evidence_id']],'status':'SUPPORTED','pooled_effect_g':None} for e in evidence]
 outcomes=[]
 for token in ['completion_time','accuracy']:
  rows=[e for e in evidence if e['outcome_type']==token]
  outcomes.append({'outcome_type':token,**{f'{d}_count':sum(e['effect_direction']==d for e in rows) for d in ['positive','negative','null']},'evidence_ids':[e['evidence_id'] for e in rows]})
 return {'meta':{'skill':'eduevidence','domain':'policy','version':'6.0.0','mode':'platform_native','question':q,'data_origin':'manual_curated'},'research_frame':frame,'decision':decision,'sources':sources,'evidence':evidence,'claims':claims,'outcomes':outcomes,'methodology_reviews':[methodology],'applicability':{'suitable_for':conditions[0],'required_conditions':conditions,'not_suitable_for':decision['what_cannot_be_claimed'][0]},'intervention':intervention,'evaluation':evaluation,'forest_plot_data':[]}

def write(name,obj): (HERE/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')

def main():
 en,zh=make('en'),make('zh');write('result.json',en);write('result.zh.json',zh)
 for name,key in [('frame','research_frame'),('verdict','decision'),('intervention','intervention'),('evaluation','evaluation')]: write(name+'.json',en[key])
 write('methodology.json',en['methodology_reviews'][0])
 for name in ['sources','evidence','claims']:
  (HERE/(name+'.jsonl')).write_text(''.join(json.dumps(row,ensure_ascii=False)+'\n' for row in en[name]))
 write('report_spec.json',{'title':en['meta']['question'],'theme':'claude','mode':'demo','sections':[{'id':key,'title':title,'component':component,'data_ref':key} for key,title,component in [('decision','Decision and boundaries','DecisionCard'),('evidence','Direct and indirect evidence','EvidenceMatrix'),('methodology_reviews','Methodological limits','MethodologyPanel'),('applicability','Deployment conditions','ApplicabilityCard'),('intervention','Proposed pilot','InterventionTimeline'),('evaluation','Evaluation and stopping','EvaluationFlow'),('sources','Verified primary sources','SourceList')]],'extensions':{'data_origin':'manual_curated','domain':'policy','benchmark_eligible':False,'render_status':'not_generated'}})
 # Graph constructor defaults contain numeric placeholders: override every unsupported estimate explicitly.
 import sys
 sys.path.insert(0,str(HERE.parents[1]))
 from engine.evidence_graph import EvidenceGraph,PaperNode,EvidenceNode,ClaimNode,OutcomeNode,GapNode,DecisionNode,GraphEdge
 g=EvidenceGraph(project_id='workplace-ai-assistant');g.created_at=g.updated_at=DATE+'T00:00:00Z'
 g.intent={'domain':'policy','question':en['meta']['question'],'data_origin':'manual_curated','benchmark_eligible':False,'timestamp_note':'Date-only curation marker, not execution time.'}
 for s in en['sources']: g.papers[s['source_id']]=PaperNode(paper_id=s['source_id'],title=s['title'],authors=s['authors'],year=s['year'],doi=s['doi'],url=s['canonical_url'])
 for e in en['evidence']:
  g.evidence[e['evidence_id']]=EvidenceNode(evidence_id=e['evidence_id'],paper_id=e['source_id'],outcome_metric=e['outcome_measure'],outcome_dimension='Policy',claim_id=e['claim_id'],outcome_id=e['outcome_type'],effect_size={'metric':'not_standardized','value':None,'ci_lower':None,'ci_upper':None,'p_value':None},sample_size=e['sample_size'],sample_description=e['population'],study_design=e['study_type'],direction='SUPPORTS',confidence_score=None,wwc_rating='Not applicable: organizational policy',calibrated_weight=None,bias_flag='; '.join(e['limitations']))
  g.claims[e['claim_id']]=ClaimNode(claim_id=e['claim_id'],statement=e['claim'],outcome_dimension='Policy',status='SUPPORTED',pooled_effect_g=None,evidence_ids=[e['evidence_id']])
  g.edges.extend([GraphEdge(e['evidence_id'],e['source_id'],'EXTRACTED_FROM'),GraphEdge(e['evidence_id'],e['claim_id'],'SUPPORTS'),GraphEdge(e['evidence_id'],e['outcome_type'],'MEASURES'),GraphEdge(e['evidence_id'],'G-001','IDENTIFIES_GAP'),GraphEdge(e['claim_id'],'D-001','GROUNDS_DECISION')])
 for o in en['outcomes']:g.outcomes[o['outcome_type']]=OutcomeNode(outcome_id=o['outcome_type'],name=o['outcome_type'],dimension='Policy',category='Policy')
 g.gaps['G-001']=GapNode(gap_id='G-001',gap_type='Local applicability and safety',description=en['decision']['missing_evidence'][0],existing_evidence_summary='E-001 through E-004',recommended_trial_design=en['evaluation']['analysis_plan'])
 g.decision=DecisionNode(decision_id='D-001',verdict='PILOT',confidence_score=None,rationale=en['decision']['decision_rationale'],intervention_plan=en['intervention'],evaluation_plan=en['evaluation'],stop_conditions=en['intervention']['stop_conditions'],timestamp=DATE+'T00:00:00Z')
 write('evidence_graph.json',g.to_dict())
if __name__=='__main__':main()
